[rewrite_local]
^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers) url script-request-header https://raw.githubusercontent.com/Cthinhdzs1tg/Locket-Gold/refs/heads/main/locketgold.js
^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$) url script-response-body https://raw.githubusercontent.com/Cthinhdzs1tg/Locket-Gold/refs/heads/main/locketgold.js

[mitm]
hostname = api.revenuecat.com
